export const EMPRESA_REQUEST = "EMPRESA_REQUEST";
export const EMPRESA_SUCCESS = "EMPRESA_SUCCESS";
export const EMPRESA_FAIL = "EMPRESA_FAIL";

export const OBTENER_EMPRESA_EDITAR = "OBTENER_EMPRESA_EDITAR";



