export const OFERTA_REQUEST = "OFERTA_REQUEST";
export const OFERTA_SUCCESS = "OFERTA_SUCCESS";
export const OFERTA_FAIL = "OFERTA_FAIL";

export const OFERTA_CREATE_REVIEW_REQUEST = 'OFERTA_CREATE_REVIEW_REQUEST'
export const OFERTA_CREATE_REVIEW_SUCCESS = 'OFERTA_CREATE_REVIEW_SUCCESS'
export const OFERTA_CREATE_REVIEW_FAIL = 'OFERTA_CREATE_REVIEW_FAIL'
export const OFERTA_CREATE_REVIEW_RESET = 'OFERTA_CREATE_REVIEW_RESET'

export const OFERTA_TOP_REQUEST = 'OFERTA_TOP_REQUEST'
export const OFERTA_TOP_SUCCESS = 'OFERTA_TOP_SUCCESS'
export const OFERTA_TOP_FAIL = 'OFERTA_TOP_FAIL'

export const OBTENER_OFERTA_DETAIL = "OBTENER_OFERTA_DETAIL";