export const OFERTA_REQUEST = "OFERTA_REQUEST";
export const OFERTA_SUCCESS = "OFERTA_SUCCESS";
export const OFERTA_FAIL = "OFERTA_FAIL";

export const OFERTA_DETAIL_REQUEST = "OFERTA_DETAIL_REQUEST";
export const OFERTA_DETAIL_SUCCESS = "OFERTA_DETAIL_SUCCESS";
export const OFERTA_DETAIL_FAIL = "OFERTA_DETAIL_FAIL";

export const REVIEW_REQUEST = "REVIEW_REQUEST";
export const REVIEW_SUCCESS = "REVIEW_SUCCESS";
export const REVIEW_FAIL = "REVIEW_FAIL";