# Generated by Django 4.1.3 on 2022-11-23 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=255)),
                ('razon_social', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=25)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descuento', models.IntegerField(max_length=2)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Categoria', models.ManyToManyField(blank=True, to='base.categoria')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('oferta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.oferta')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
