# Generated by Django 4.1.3 on 2022-11-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
