# Generated by Django 4.1.3 on 2022-11-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_empresa_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='nombre',
            new_name='name',
        ),
    ]
