# Generated by Django 4.1.3 on 2022-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_nombre_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(default='lorem ipsum', max_length=600),
        ),
    ]
