# Generated by Django 4.1.3 on 2022-11-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_empresa_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
